# Usa l'immagine ufficiale di .NET SDK per la compilazione
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /app

# Copia i file di progetto e ripristina le dipendenze
COPY *.csproj ./
RUN dotnet restore

# Copia il resto dei file sorgente e compila l'applicazione
COPY . ./
RUN dotnet publish -c Release -o out

# Usa un'immagine più leggera per l'esecuzione effettiva dell'applicazione
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build-env /app/out .

# Imposta la variabile d'ambiente per le porte (opzionale, ma buona pratica)
ENV ASPNETCORE_URLS=http://+:5141

EXPOSE 5141

# Comando per avviare l'applicazione
ENTRYPOINT ["dotnet", "GameShelf.API.dll"]